"""The eHall certificate pipeline: a typed contract, not a browser session (ADR-0025).

This module is the *shape* of one whitelisted errand: the certificate application service. It
knows nothing about browsers, selectors or Playwright — those live in `adapters/ehall/` — and it
knows nothing about approval or execution, which are Phase 6A's.

What it does own is the thing that makes an approval meaningful here. A page can be changed by the
university at any time, so the pipeline records a **page contract**: the service identity, the
ordered field definitions and their options, the required materials and the submit control. Its
SHA-256 becomes part of the action payload, and anything that does not match it exactly fails
closed before a single value is typed.

Nothing in this module can fill anything, and nothing here can submit anything.
"""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass
from enum import StrEnum

from assistant.domain.errors import EHallUnsupportedRequiredField, InvalidEHallForm

PIPELINE_ID = "ehall.nju.certificate"
"""The one pipeline this project implements. It is not a parameter anywhere."""

PAGE_CONTRACT_VERSION = 1
"""Bump when the shape this pipeline expects changes; it is part of the fingerprint."""

CERTIFICATE_SCHEMA_VERSION = 1

CERTIFICATE_SERVICE_NAME = "证明书申请"
"""The exact service title the adapter looks for. Zero or several matches both fail."""

CERTIFICATE_SERVICE_IDENTITY = "nju-ehall/证明书申请"

CERTIFICATE_CONSEQUENCE = (
    "Submitting this action creates a certificate application in the NJU eHall and may create an "
    "administrative record visible to university staff. Review every field before approving: the "
    "university processes what was submitted, and this project cannot withdraw it for you."
)
"""Fixed local text. It is never generated by a model and never read from the page."""

MAX_FIELDS = 40
MAX_MATERIALS = 20
MAX_FIELD_LABEL_CHARS = 200
MAX_FIELD_VALUE_CHARS = 2000
MAX_OPTIONS = 60

FIELD_KEY_PATTERN = re.compile(r"^[A-Za-z][A-Za-z0-9_.:-]{0,63}$")


class EHallFieldKind(StrEnum):
    """The control types this pipeline will fill.

    Anything else — a file upload, a rich text editor, an unknown widget — is *unsupported*, not
    "best effort". A required control the project cannot fill means the user has to do this errand
    by hand.
    """

    TEXT = "text"
    TEXTAREA = "textarea"
    SELECT = "select"
    RADIO = "radio"


@dataclass(frozen=True, slots=True)
class EHallFieldDefinition:
    """One fillable field, as the live page described it."""

    key: str
    label: str
    kind: EHallFieldKind
    required: bool = True
    options: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        if not FIELD_KEY_PATTERN.match(self.key):
            raise InvalidEHallForm(
                f"a field key must match {FIELD_KEY_PATTERN.pattern}, not {self.key!r}"
            )
        label = " ".join(self.label.split())
        if not label:
            raise InvalidEHallForm("a field needs a label")
        if len(label) > MAX_FIELD_LABEL_CHARS:
            raise InvalidEHallForm(
                f"a field label must be at most {MAX_FIELD_LABEL_CHARS} characters"
            )
        object.__setattr__(self, "label", label)
        if len(self.options) > MAX_OPTIONS:
            raise InvalidEHallForm(f"a field may offer at most {MAX_OPTIONS} options")
        if self.kind in (EHallFieldKind.SELECT, EHallFieldKind.RADIO):
            if not self.options:
                raise InvalidEHallForm(
                    f"a {self.kind} field must offer its allowed options"
                )
        elif self.options:
            raise InvalidEHallForm("only a select or radio field carries options")

    def to_payload(self) -> dict[str, object]:
        """The canonical description used in the page contract and in the fingerprint."""
        return {
            "key": self.key,
            "label": self.label,
            "kind": self.kind.value,
            "required": self.required,
            "options": list(self.options),
        }


@dataclass(frozen=True, slots=True)
class EHallUnsupportedControl:
    """A control the pipeline will not fill, with why it matters."""

    label: str
    description: str
    required: bool

    def __post_init__(self) -> None:
        if not self.label.strip() or not self.description.strip():
            raise InvalidEHallForm("an unsupported control needs a label and a description")


@dataclass(frozen=True, slots=True)
class EHallFormSnapshot:
    """One read-only observation of the certificate form."""

    service_identity: str
    fields: tuple[EHallFieldDefinition, ...]
    required_materials: tuple[str, ...] = ()
    unsupported: tuple[EHallUnsupportedControl, ...] = ()
    submit_control: str = ""
    page_markers: tuple[str, ...] = ()
    pipeline_id: str = PIPELINE_ID
    page_contract_version: int = PAGE_CONTRACT_VERSION

    def __post_init__(self) -> None:
        if not self.service_identity.strip():
            raise InvalidEHallForm("a form snapshot needs a service identity")
        if not self.fields:
            raise InvalidEHallForm("a form snapshot needs at least one fillable field")
        if len(self.fields) > MAX_FIELDS:
            raise InvalidEHallForm(f"a form may have at most {MAX_FIELDS} fields")
        keys = [item.key for item in self.fields]
        if len(set(keys)) != len(keys):
            raise InvalidEHallForm("field keys must be unique within one form")
        if len(self.required_materials) > MAX_MATERIALS:
            raise InvalidEHallForm(
                f"a form may list at most {MAX_MATERIALS} required materials"
            )
        if not self.submit_control.strip():
            raise InvalidEHallForm("a form snapshot needs the identity of its submit control")

    @property
    def required_unsupported(self) -> tuple[EHallUnsupportedControl, ...]:
        """Unsupported controls the university requires — the pipeline refuses to continue."""
        return tuple(item for item in self.unsupported if item.required)

    def require_supported(self) -> None:
        """Refuse a form with a required control this pipeline cannot fill.

        Raises:
            EHallUnsupportedRequiredField: a required control is unsupported.
        """
        blocking = self.required_unsupported
        if blocking:
            labels = ", ".join(item.label for item in blocking)
            raise EHallUnsupportedRequiredField(
                f"the certificate form requires controls this pipeline cannot fill: {labels}"
            )

    def fingerprint(self) -> str:
        """The page-contract fingerprint: canonical JSON in, SHA-256 out."""
        return page_contract_fingerprint(
            pipeline_id=self.pipeline_id,
            page_contract_version=self.page_contract_version,
            service_identity=self.service_identity,
            page_markers=self.page_markers,
            fields=self.fields,
            required_materials=self.required_materials,
            submit_control=self.submit_control,
        )

    def to_payload(self) -> dict[str, object]:
        """The whole contract as data, for preview and for tests."""
        return {
            "pipeline_id": self.pipeline_id,
            "page_contract_version": self.page_contract_version,
            "service_identity": self.service_identity,
            "page_markers": list(self.page_markers),
            "submit_control": self.submit_control,
            "required_materials": list(self.required_materials),
            "fields": [item.to_payload() for item in self.fields],
        }


def page_contract_fingerprint(
    *,
    pipeline_id: str,
    page_contract_version: int,
    service_identity: str,
    page_markers: tuple[str, ...],
    fields: tuple[EHallFieldDefinition, ...],
    required_materials: tuple[str, ...],
    submit_control: str,
) -> str:
    """Canonical fingerprint of exactly what the pipeline expects to find.

    Ordering matters and is preserved: a form that reorders its fields is a form whose fill-step
    the user has not reviewed. Python's `hash()` is never used — it is seeded per process and
    would make the fingerprint meaningless across runs.
    """
    payload = {
        "pipeline_id": pipeline_id,
        "page_contract_version": page_contract_version,
        "service_identity": service_identity,
        "page_markers": list(page_markers),
        "fields": [item.to_payload() for item in fields],
        "required_materials": list(required_materials),
        "submit_control": submit_control,
    }
    canonical = json.dumps(
        payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


@dataclass(frozen=True, slots=True)
class EHallCertificateFieldValue:
    """One value the user supplied, paired with what the page called that field."""

    key: str
    label: str
    kind: EHallFieldKind
    value: str

    def __post_init__(self) -> None:
        if not self.key.strip():
            raise InvalidEHallForm("a field value needs a key")
        if not self.label.strip():
            raise InvalidEHallForm("a field value needs the label it was reviewed under")
        text = self.value.strip()
        if not text:
            raise InvalidEHallForm(f"field {self.key!r} needs a non-blank value")
        if len(text) > MAX_FIELD_VALUE_CHARS:
            raise InvalidEHallForm(
                f"field {self.key!r} must be at most {MAX_FIELD_VALUE_CHARS} characters"
            )
        object.__setattr__(self, "value", text)

    def to_payload(self) -> dict[str, object]:
        """The JSON form stored in the approved action."""
        return {
            "key": self.key,
            "label": self.label,
            "kind": self.kind.value,
            "value": self.value,
        }

    @classmethod
    def from_payload(cls, payload: object) -> EHallCertificateFieldValue:
        """Rebuild one value from an approved action, refusing anything unexpected."""
        if not isinstance(payload, dict):
            raise InvalidEHallForm("a stored field value must be a JSON object")
        expected = {"key", "label", "kind", "value"}
        if set(payload) != expected:
            raise InvalidEHallForm("a stored field value has unexpected fields")
        return cls(
            key=_text(payload, "key"),
            label=_text(payload, "label"),
            kind=_field_kind(payload.get("kind")),
            value=_text(payload, "value"),
        )


def _text(payload: dict[str, object], key: str) -> str:
    value = payload[key]
    if not isinstance(value, str):
        raise InvalidEHallForm(f"{key} must be a string")
    return value


def _field_kind(value: object) -> EHallFieldKind:
    if not isinstance(value, str):
        raise InvalidEHallForm("a field kind must be a string")
    try:
        return EHallFieldKind(value)
    except ValueError as exc:
        raise InvalidEHallForm(f"unknown field kind {value!r}") from exc


@dataclass(frozen=True, slots=True)
class EHallCertificatePayload:
    """The exact, immutable errand that has to be approved before anything is typed."""

    fields: tuple[EHallCertificateFieldValue, ...]
    page_contract_fingerprint: str
    required_materials: tuple[str, ...] = ()
    service_identity: str = CERTIFICATE_SERVICE_IDENTITY
    pipeline_id: str = PIPELINE_ID
    page_contract_version: int = PAGE_CONTRACT_VERSION
    schema_version: int = CERTIFICATE_SCHEMA_VERSION
    consequence: str = CERTIFICATE_CONSEQUENCE

    def __post_init__(self) -> None:
        if self.schema_version != CERTIFICATE_SCHEMA_VERSION:
            raise InvalidEHallForm(
                f"unsupported certificate schema version {self.schema_version}"
            )
        if not self.fields:
            raise InvalidEHallForm("a certificate action needs at least one field value")
        keys = [item.key for item in self.fields]
        if len(set(keys)) != len(keys):
            raise InvalidEHallForm("a certificate action must not repeat a field key")
        if not re.fullmatch(r"[0-9a-f]{64}", self.page_contract_fingerprint):
            raise InvalidEHallForm(
                "a page contract fingerprint must be 64 lowercase hex characters"
            )
        if self.service_identity.strip() != CERTIFICATE_SERVICE_IDENTITY:
            raise InvalidEHallForm("a certificate action names the whitelisted service only")
        if self.pipeline_id.strip() != PIPELINE_ID:
            raise InvalidEHallForm("a certificate action names the whitelisted pipeline only")
        if self.consequence.strip() != CERTIFICATE_CONSEQUENCE:
            raise InvalidEHallForm("the consequence text is fixed locally and never edited")

    def to_payload(self) -> dict[str, object]:
        """The canonical JSON document stored in the immutable `ActionRequest`."""
        return {
            "schema_version": self.schema_version,
            "pipeline_id": self.pipeline_id,
            "page_contract_version": self.page_contract_version,
            "page_contract_fingerprint": self.page_contract_fingerprint,
            "service_identity": self.service_identity,
            "fields": [item.to_payload() for item in self.fields],
            "required_materials": list(self.required_materials),
            "consequence": self.consequence,
        }

    @classmethod
    def from_payload(cls, payload: object) -> EHallCertificatePayload:
        """Rebuild the payload from an approved action, refusing anything unexpected.

        This is what the executor reads, so it is strict: a missing field, an extra key or an
        unknown kind is an error, not a default.

        Raises:
            InvalidEHallForm: the payload is not a usable certificate action.
        """
        if not isinstance(payload, dict):
            raise InvalidEHallForm("a certificate payload must be a JSON object")
        expected = {
            "schema_version",
            "pipeline_id",
            "page_contract_version",
            "page_contract_fingerprint",
            "service_identity",
            "fields",
            "required_materials",
            "consequence",
        }
        if set(payload) != expected:
            missing = sorted(expected - set(payload))
            extra = sorted(set(payload) - expected)
            raise InvalidEHallForm(
                f"a certificate payload has the wrong fields "
                f"(missing {missing}, extra {extra})"
            )
        raw_fields = payload["fields"]
        if not isinstance(raw_fields, list):
            raise InvalidEHallForm("fields must be a list")
        materials = payload["required_materials"]
        if not isinstance(materials, list):
            raise InvalidEHallForm("required_materials must be a list")
        return cls(
            fields=tuple(
                EHallCertificateFieldValue.from_payload(item) for item in raw_fields
            ),
            page_contract_fingerprint=_text(payload, "page_contract_fingerprint"),
            required_materials=tuple(str(item) for item in materials),
            service_identity=_text(payload, "service_identity"),
            pipeline_id=_text(payload, "pipeline_id"),
            page_contract_version=_int(payload, "page_contract_version"),
            schema_version=_int(payload, "schema_version"),
            consequence=_text(payload, "consequence"),
        )


def _int(payload: dict[str, object], key: str) -> int:
    value = payload[key]
    if not isinstance(value, int) or isinstance(value, bool):
        raise InvalidEHallForm(f"{key} must be an integer")
    return value


def build_field_values(
    snapshot: EHallFormSnapshot, supplied: dict[str, str]
) -> tuple[EHallCertificateFieldValue, ...]:
    """Turn the user's `--field KEY=VALUE` input into reviewed values, or refuse it.

    The rules are the point of a typed pipeline: the key must exist, every required field must be
    present, and a select or radio value must be one of the options the page actually offers.
    Nothing is inferred and nothing is defaulted.

    Raises:
        InvalidEHallForm: a key is unknown, a required field is missing, or a value is not one of
            the allowed options.
    """
    definitions = {item.key: item for item in snapshot.fields}
    unknown = sorted(set(supplied) - set(definitions))
    if unknown:
        raise InvalidEHallForm(
            "unknown field(s): "
            + ", ".join(unknown)
            + "; run `pw ehall certificate inspect` to see the current form"
        )
    values: list[EHallCertificateFieldValue] = []
    for definition in snapshot.fields:
        raw = supplied.get(definition.key)
        if raw is None or not raw.strip():
            if definition.required:
                raise InvalidEHallForm(
                    f"field {definition.key!r} ({definition.label}) is required"
                )
            continue
        value = raw.strip()
        if definition.options and value not in definition.options:
            raise InvalidEHallForm(
                f"field {definition.key!r} must be one of: {', '.join(definition.options)}"
            )
        values.append(
            EHallCertificateFieldValue(
                key=definition.key,
                label=definition.label,
                kind=definition.kind,
                value=value,
            )
        )
    if not values:  # pragma: no cover - a required field would have failed first
        raise InvalidEHallForm("a certificate action needs at least one value")
    return tuple(values)


@dataclass(frozen=True, slots=True)
class EHallCertificatePreview:
    """Everything a user needs to judge an errand before approving it."""

    service_identity: str
    fields: tuple[EHallCertificateFieldValue, ...]
    required_materials: tuple[str, ...]
    consequence: str
    page_contract_fingerprint: str
    unsupported: tuple[EHallUnsupportedControl, ...] = ()


__all__ = [
    "CERTIFICATE_CONSEQUENCE",
    "CERTIFICATE_SCHEMA_VERSION",
    "CERTIFICATE_SERVICE_IDENTITY",
    "CERTIFICATE_SERVICE_NAME",
    "FIELD_KEY_PATTERN",
    "MAX_FIELDS",
    "MAX_FIELD_VALUE_CHARS",
    "PAGE_CONTRACT_VERSION",
    "PIPELINE_ID",
    "EHallCertificateFieldValue",
    "EHallCertificatePayload",
    "EHallCertificatePreview",
    "EHallFieldDefinition",
    "EHallFieldKind",
    "EHallFormSnapshot",
    "EHallUnsupportedControl",
    "build_field_values",
    "page_contract_fingerprint",
]
