"""The first real `EventHandler`: classify one synchronized message (ADR-0021).

```text
InboundEvent(mail.message.received)
        │ payload: {account_id, mail_message_id}
        ▼
resolve the stable MailMessage ── verify the event link ──► mismatch: retry
        │
        ▼
ensure deterministic thread (code, never a model)
        │
        ▼
bounded untrusted thread context
        │
        ├── stored analysis with the same fingerprint? ──► reuse it, no model call
        ▼
StructuredModel (closed schema) ──► local semantic validation ──► MailAnalysis
```

The handler writes exactly one kind of durable state: an analysis. It cannot create a task, a
case, a deadline, a calendar event, a notification or an outbound message, because nothing in
its imports can — and because the schema it sends has nowhere to put one.

Failure classification is deliberately split. A provider that is throttled, briefly down or
answering with unusable JSON is *retryable*: the next attempt may succeed, and the existing
EventWorker already bounds how many attempts are spent. A provider that rejects the credential,
has no balance, or refuses the request as malformed will not behave differently the second time,
so it is a `PermanentEventError` and the event dead-letters immediately instead of burning the
retry budget. Either way the mail itself is untouched: a model failure is never a reason for a
stored message to change or disappear.
"""

from __future__ import annotations

import json
import logging
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any
from uuid import UUID

from assistant.application.mail_analysis import (
    parse_mail_analysis_output,
    unavailable_body_analysis,
)
from assistant.application.mail_analysis_prompt import MAIL_ANALYSIS_INSTRUCTIONS
from assistant.application.mail_analysis_schema import (
    MAIL_ANALYSIS_SCHEMA_V1,
    MAIL_ANALYSIS_SCHEMA_VERSION,
)
from assistant.application.mail_context import MailContext, MailContextBuilder
from assistant.application.mail_threading import MailThreadLinker
from assistant.application.structured_model import StructuredModel
from assistant.domain.errors import (
    MailEventLinkMismatch,
    MailMessageNotFound,
    ModelAuthenticationError,
    ModelBillingError,
    ModelConfigurationError,
    ModelCredentialsMissing,
    ModelInvalidRequest,
    ModelNotConfigured,
    ModelOutputNotJson,
    ModelOutputSchemaViolation,
    ModelProtocolError,
    ModelRateLimited,
    ModelResponseIncomplete,
    ModelTransientError,
    ModelUnavailable,
    PermanentEventError,
)
from assistant.domain.inbound_event import InboundEvent
from assistant.domain.mail import MailBodyStatus, MailMessageId
from assistant.domain.mail_analysis import ANALYZER_VERSION, mail_analysis_input_fingerprint
from assistant.domain.model import (
    ModelMessage,
    ModelOutputMode,
    ModelReasoningEffort,
    ModelRequest,
    ModelRole,
)
from assistant.ports.clock import Clock
from assistant.ports.event_handler import EventHandler
from assistant.ports.mail_intelligence_repository import MailIntelligenceRepository
from assistant.ports.mail_repository import MailRepository

LOGGER = logging.getLogger("assistant.mail")

MAIL_EVENT_TYPE = "mail.message.received"
"""The `InboundEvent` type this handler accepts."""

PERMANENT_MODEL_ERRORS = (
    ModelAuthenticationError,
    ModelBillingError,
    ModelInvalidRequest,
    ModelCredentialsMissing,
    ModelConfigurationError,
    ModelNotConfigured,
)
"""Provider failures that a second identical attempt cannot fix."""

RETRYABLE_MODEL_ERRORS = (
    ModelRateLimited,
    ModelTransientError,
    ModelUnavailable,
    ModelProtocolError,
    ModelResponseIncomplete,
    ModelOutputNotJson,
    ModelOutputSchemaViolation,
)
"""Provider or output failures that are retried under the EventWorker's bounded policy.

Structured output is generated by a model, so a malformed answer is a *transient* property of
that generation rather than a broken request: the next attempt may well satisfy the schema. The
retry budget, not this module, decides when that stops being worth trying.
"""


@dataclass(frozen=True, slots=True)
class MailEventPayload:
    """The two facts a mail event is allowed to carry."""

    account_id: str
    message_id: MailMessageId


class MailInboundEventHandler:
    """Turns a received mail event into a durable analysis. Nothing else."""

    def __init__(
        self,
        mail: MailRepository,
        intelligence: MailIntelligenceRepository,
        linker: MailThreadLinker,
        context_builder: MailContextBuilder,
        model: StructuredModel,
        clock: Clock,
        *,
        analyzer_version: int = ANALYZER_VERSION,
        reasoning_effort: str = "low",
        max_output_tokens: int = 4096,
    ) -> None:
        self._mail = mail
        self._intelligence = intelligence
        self._linker = linker
        self._context_builder = context_builder
        self._model = model
        self._clock = clock
        self._analyzer_version = analyzer_version
        self._reasoning_effort = reasoning_effort
        self._max_output_tokens = max_output_tokens

    async def handle(self, event: InboundEvent) -> None:
        """Analyze the message this event names, once.

        Raises:
            PermanentEventError: the event type is not this handler's, or its payload is not the
                exact identity document the bridge writes.
            MailEventLinkMismatch: the event and the stored link disagree; retryable, because
                the mail sync bridge repairs the link on its next round.
            MailMessageNotFound: the named message is not stored; retryable and bounded.
            PermanentEventError: the provider refused the request in a way retrying cannot fix.
        """
        if event.event_type != MAIL_EVENT_TYPE:
            raise PermanentEventError(
                f"mail handler does not accept event type {event.event_type!r}"
            )
        payload = parse_mail_event_payload(event)
        message = await self._mail.get_message(payload.message_id)
        if message is None:
            raise MailMessageNotFound(payload.message_id)
        if message.account_id != payload.account_id:
            raise MailEventLinkMismatch(
                f"event {event.id} names account {payload.account_id!r} but message "
                f"{message.id} belongs to {message.account_id!r}"
            )
        if await self._mail.get_linked_event_id(message.id) != event.id:
            # Both crash windows end here: either the link has not been written yet (the mail
            # sync bridge writes it moments after ingesting) or it points somewhere else. The
            # event is retried rather than analyzed under an identity that does not hold.
            raise MailEventLinkMismatch(
                f"event {event.id} is not linked to mail message {message.id}"
            )
        member = await self._linker.ensure_thread(message.id)
        context = await self._context_builder.build(message, member.thread_id)
        fingerprint = mail_analysis_input_fingerprint(
            analyzer_version=self._analyzer_version,
            schema_version=MAIL_ANALYSIS_SCHEMA_VERSION,
            message_id=message.id,
            content_fingerprint=message.content_fingerprint,
            thread_message_ids=context.thread_message_ids,
            thread_content_fingerprints=context.thread_content_fingerprints,
            planning_timezone=context.planning_timezone,
        )
        stored = await self._intelligence.get_analysis(message.id)
        if (
            stored is not None
            and stored.analyzer_version == self._analyzer_version
            and stored.input_fingerprint == fingerprint
        ):
            # A retried event must not pay for an analysis it already has. This is the whole
            # reason the fingerprint is stored next to the result.
            LOGGER.debug("mail analysis reused message=%s", message.id)
            return
        now = self._clock.now()
        if message.body_status is MailBodyStatus.OVERSIZE:
            await self._intelligence.persist_analysis(
                unavailable_body_analysis(
                    message_id=message.id,
                    input_fingerprint=fingerprint,
                    now=now,
                    analyzer_version=self._analyzer_version,
                )
            )
            LOGGER.info("mail analysis skipped message=%s reason=body-oversize", message.id)
            return
        analysis = parse_mail_analysis_output(
            await self._complete(context),
            message_id=message.id,
            input_fingerprint=fingerprint,
            now=now,
            analyzer_version=self._analyzer_version,
        )
        await self._intelligence.persist_analysis(analysis)
        # Counts and a category only: never a subject, an address or a body.
        LOGGER.info(
            "mail analyzed account=%s category=%s candidates=%d",
            message.account_id,
            analysis.category.value,
            len(analysis.action_candidates),
        )

    async def _complete(self, context: MailContext) -> dict[str, Any]:
        """Call the model, mapping provider failures onto the existing retry policy."""
        request = ModelRequest(
            instructions=MAIL_ANALYSIS_INSTRUCTIONS,
            messages=(ModelMessage(role=ModelRole.USER, content=context.to_json()),),
            output_mode=ModelOutputMode.JSON_SCHEMA,
            json_schema=MAIL_ANALYSIS_SCHEMA_V1,
            reasoning_effort=ModelReasoningEffort(self._reasoning_effort),
            max_output_tokens=self._max_output_tokens,
        )
        try:
            return await self._model.complete_json(request)
        except PermanentEventError:
            raise
        except PERMANENT_MODEL_ERRORS as exc:
            raise PermanentEventError(str(exc)) from exc


def parse_mail_event_payload(event: InboundEvent) -> MailEventPayload:
    """Read the identity payload of a mail event.

    The payload carries identity and nothing else: a subject, a body or an attachment name in an
    event row would duplicate mail content into the event log. Anything that is not exactly the
    two expected keys is a permanent failure of the producer, not something to guess around.

    Raises:
        PermanentEventError: the payload is missing, malformed or carries extra keys.
    """
    if event.content is None:
        raise PermanentEventError(f"event {event.id} carries no mail payload")
    try:
        decoded = json.loads(event.content)
    except json.JSONDecodeError as exc:
        raise PermanentEventError(f"event {event.id} payload is not JSON: {exc.msg}") from exc
    if not isinstance(decoded, dict):
        raise PermanentEventError(f"event {event.id} payload is not a JSON object")
    if set(decoded) != {"account_id", "mail_message_id"}:
        raise PermanentEventError(
            f"event {event.id} payload keys are {sorted(decoded)}, expected exactly "
            "account_id and mail_message_id"
        )
    account_id = decoded["account_id"]
    raw_message_id = decoded["mail_message_id"]
    if not isinstance(account_id, str) or not account_id.strip():
        raise PermanentEventError(f"event {event.id} payload has no account id")
    if not isinstance(raw_message_id, str):
        raise PermanentEventError(f"event {event.id} payload has no message id")
    try:
        message_id = UUID(raw_message_id)
    except ValueError as exc:
        raise PermanentEventError(
            f"event {event.id} payload message id is not a UUID"
        ) from exc
    return MailEventPayload(account_id=account_id, message_id=message_id)


class InboundEventDispatcher:
    """Routes an event to the one handler registered for its type.

    A map with one entry, deliberately: an unknown event type is dead-lettered rather than
    silently accepted, and there is no plugin registry, no dynamic import and no tool loop that
    could turn a new event type into new authority.
    """

    def __init__(self, handlers: Mapping[str, EventHandler]) -> None:
        if not handlers:
            raise ValueError("a dispatcher needs at least one handler")
        self._handlers = dict(handlers)

    @property
    def event_types(self) -> tuple[str, ...]:
        """The event types this dispatcher accepts, sorted."""
        return tuple(sorted(self._handlers))

    async def handle(self, event: InboundEvent) -> None:
        """Handle `event`, or refuse it permanently when nothing claims its type."""
        handler = self._handlers.get(event.event_type)
        if handler is None:
            raise PermanentEventError(
                f"no handler is registered for event type {event.event_type!r}"
            )
        await handler.handle(event)


__all__ = [
    "MAIL_EVENT_TYPE",
    "PERMANENT_MODEL_ERRORS",
    "RETRYABLE_MODEL_ERRORS",
    "InboundEventDispatcher",
    "MailEventPayload",
    "MailInboundEventHandler",
    "parse_mail_event_payload",
]
