"""Structured model output: ask for JSON, then validate it locally (ADR-0017).

The whole point of this module is the word *locally*:

```text
ModelPort.complete(request with a JSON schema)
        │
        ▼
final text ──► json.loads ──► Draft202012Validator.validate ──► dict
                    │                     │
                    └── invalid ──────────┴──► ModelOutput* error, and no caller sees a value
```

A provider's structured-output mode is a *convenience*, not a guarantee: it is generated by a
model, and model output is untrusted input. Server-side conformance never replaces a
deterministic check performed by code that owns the contract.
"""

from __future__ import annotations

import json
from typing import Any

from jsonschema.exceptions import SchemaError, ValidationError
from jsonschema.validators import Draft202012Validator

from assistant.domain.errors import (
    InvalidModelSchema,
    ModelOutputNotJson,
    ModelOutputSchemaViolation,
    ModelProtocolError,
)
from assistant.domain.model import (
    JsonSchemaOutput,
    ModelOutputMode,
    ModelRequest,
    ModelResponse,
)
from assistant.ports.model import ModelPort


def validate_json_schema(schema: JsonSchemaOutput) -> None:
    """Check that `schema` is a usable Draft 2020-12 schema before anything is sent.

    Raises:
        InvalidModelSchema: the schema itself is malformed.
    """
    try:
        Draft202012Validator.check_schema(schema.schema)
    except SchemaError as exc:
        raise InvalidModelSchema(f"invalid JSON schema: {exc.message}") from exc


class StructuredModel:
    """Turns a model request into locally validated structured data."""

    def __init__(self, model: ModelPort) -> None:
        self._model = model

    async def complete_json(self, request: ModelRequest) -> dict[str, Any]:
        """Run `request` and return the validated JSON object it produced.

        Raises:
            InvalidModelSchema: the request's schema is not a valid JSON Schema.
            ModelOutputNotJson: the final text is not a JSON object.
            ModelOutputSchemaViolation: the JSON does not satisfy the schema.
        """
        if request.output_mode is not ModelOutputMode.JSON_SCHEMA:
            raise ModelProtocolError(
                "structured output requires a JSON_SCHEMA request"
            )
        schema = request.json_schema
        if schema is None:  # pragma: no cover - ModelRequest already guarantees this
            raise ModelProtocolError("structured output requires a schema")
        validate_json_schema(schema)
        response = await self._model.complete(request)
        return parse_structured_output(response, schema)


def parse_structured_output(
    response: ModelResponse, schema: JsonSchemaOutput
) -> dict[str, Any]:
    """Parse and validate one structured response, or explain precisely why it is unusable."""
    text = response.text.strip()
    if not text:
        raise ModelOutputNotJson("the model returned no text to parse")
    try:
        decoded = json.loads(text)
    except json.JSONDecodeError as exc:
        raise ModelOutputNotJson(f"model output is not valid JSON: {exc.msg}") from exc
    if not isinstance(decoded, dict):
        raise ModelOutputNotJson(
            f"model output must be a JSON object, not {type(decoded).__name__}"
        )
    validator = Draft202012Validator(schema.schema)
    error = next(validator.iter_errors(decoded), None)
    if error is not None:
        raise ModelOutputSchemaViolation(_describe(error))
    return decoded


def _describe(error: ValidationError) -> str:
    """A short, deterministic explanation: JSON path and validator, never the whole output."""
    location = "/".join(str(part) for part in error.absolute_path) or "<root>"
    return (
        f"model output violates schema {error.validator!r} at {location}: {error.message}"
    )


__all__ = ["StructuredModel", "parse_structured_output", "validate_json_schema"]
